/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.repository.mmf;

public class App {
    public String getGreeting() {
        return "Hello world. Once again useless text. Again";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
