/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.repository.mmf;

public class App {
    public String getGreeting() {
        String speech = "Now is the time for all good people to come to the aid of their country Change.";
        String substr1 = speech.substring(-1, speech.length());  // Noncompliant; start and end values both bad
        String substr2 = speech.substring(speech.length(), 0); // Noncompliant, start value must be < end value
        char ch = speech.charAt(speech.length());  // Noncompliant
        return "";    
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
